db_type: postgresql
db_name: app_database
db_user: app_user
db_password: secure_password
container_name: postgres_container

backup_dir: /tmp/db_migration
backup_file: "{{ backup_dir }}/migration_{{ ansible_date_time.epoch }}.sql"

native_db_port: 5432
native_db_service: postgresql
