---
- name: Restore PostgreSQL database
  shell: |
    psql {{ db_name }} < {{ backup_file }}
  become: true
  become_user: _postgresql
  register: restore_result

- name: Display restore result
  debug:
    msg: "Database restoration completed"
